channels:
    - conda-forge
dependencies:
    - jupyter
    - jupyterlab
    - scipy
    - numpy
    - matplotlib
    - pillow
    - pandas
    - voila
    - ipympl
    - vpython==7.6.3
    - jupyterlab-vpython==3.1.3